spring.application.name=duemate

spring.datasource.url=jdbc:postgresql://localhost:5432/duemate
spring.datasource.username=postgres
spring.datasource.password=jason123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-jpa=true
spring.jpa.properties.hibernate.format_sql=true